# ~/.config/alacritty/alacritty.toml

# Font configuration
[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

# Window configuration
[window]
opacity = 0.7  # Semi-transparency
startup_mode = "Maximized"  # Options: "Windowed", "Fullscreen", "Maximized", "Hidden"

[window.padding]
x = 15
y = 15

# Scrolling configuration
[scrolling]
history = 10000  # Number of lines to keep in the scrollback buffer
multiplier = 3  # Scroll speed multiplier

# Selection configuration
[selection]
save_to_clipboard = true  # Automatically save selection to clipboard
